version: "3"
services:
  mongo:
    image: mongo:6
    ports: [ "27017:27017" ]
  backend:
    build: ./backend
    depends_on: [ mongo ]
    ports: [ "5000:5000" ]
  frontend:
    build: ./frontend
    depends_on: [ backend ]
    ports: [ "3000:3000" ]
